---
output: pdf_document
---
<!--#include virtual="../header.html" -->
<!--#include virtual="../header2.html" -->


Syllabus
========

STATS 110, Statistical Methods in Engineering and the Physical Sciences
Stanford University, Department of Statistics, Autumn 2016


**************

Course Description
------------------
This is an introduction to probability and statistics for engineers and science majors. We will cover such topics as descriptive statistics, basic probability, hypothesis testing, confidence intervals, point estimation, simple linear regression, analysis of variance (ANOVA), and some nonparametric methods. We will try to use real world examples to motivate the understanding of statistical analysis. The only prerequisite is one year of calculus.

Schedule
--------

The class meets Monday through Thursday 11:30am to 12:20pm in [320-105](https://campus-map.stanford.edu/?id=01-320&lat=37.42694141&lng=-122.17188691&zoom=17&srch=320-105).  Monday, Tuesday, and Wednesday will be lectures and Thursday will be a recitation section.  

Textbook and recommended reading 
--------------------------------

We will be using Norm Matloff's free textbook From Algorithms to Z-Scores: Probabilistic and Statistical Modeling in Computer Science, available at [http://heather.cs.ucdavis.edu/~matloff/132/PLN/ProbStatBook.pdf].  We will not strictly follow the textbook, so class attendance is highly suggested.

The book's examples and homework use [R](https://cran.r-project.org/) and we shall too.    Some resources on learning R can be found at [http://heather.cs.ucdavis.edu/~matloff/R/RProg.pdf],  [https://cran.r-project.org/doc/contrib/Owen-TheRGuide.pdf], [http://r4ds.had.co.nz/],  [https://www.nceas.ucsb.edu/files/scicomp/Dloads/RProgramming/BestFirstRTutorial.pdf], and [http://www.cyclismo.org/tutorial/R/].  


Course Staff
------------

**Instructor**: Timothy Daley
**Primary Contact**: [Canvas](https://canvas.stanford.edu)
**Email**: tdaley@stanford.edu
**Office**: [Sequoia Hall](http://campus-map.stanford.edu/?id=04-530&lat=37.4289326567&lng=-122.172199549) room 105
**Office Hours**: Tuesday 1-4 pm or by appointment.


**TAs**: 
Mona Azadkia <mazadkia@stanford.edu>
Claire Donnat <cdonnat@stanford.edu>
Snigdha Panigrahi <snigdha@stanford.edu>



### Contacting Course Staff


Questions about the homework, about R, of general interest, or about course logistics are most appropriate to ask on [Canvas](https://canvas.stanford.edu/courses/47191/discussion_topics). 
Other students probably have the same question as you, so it will be helpful for everyone to see the responses.  The course staff will rotate in who replies to these questions which makes Canvas much simpler from an administrative perspective.  Receiving the questions online allows us time to give better answers than when we are asked on the fly.  It is fine to talk about the weekly homework questions on Piazza, but please talk about the problems more conceptually rather than just posting your answer.  Remember the [Stanford Honor Code](https://communitystandards.stanford.edu/student-conduct-process/honor-code-and-fundamental-standard#honor-code) still applies.



### Course objectives

My primary objective in this course is to instill in you an intuitive understanding of probability and statistics that you can apply in your daily and professional life.  This includes how to deal with data, model physical processes, and understand statistical claims (such as those you see in the news).  I will try to focus on this basic principle and appreciate any feedback.    


**********

Assignments and Evaluation
--------------------------

**Grading Breakdown**
* 30% Quizzes (10 total, no quiz in the last week)
* 40% Weekly homework (10 total, no homework the first week)
* 30% Final Exam (or final project for graduate students taking this course, see below)


**Due Dates and Exam Dates**
Homeworks will be posted Mondays on Canvas at 5pm.  They are due Fridays at 11:59pm.  Late homework will be accepted till the next homework is posted for 50 \% credit.  


**Submitting Assignments**
* All homeworks are due Friday at 11:59pm 
* Late assignments will not be graded.  
* Homeworks must be submitted through Canvas.
* The homework file name should be [your Stanford User ID]-hw[homework #].pdf (e.g., If John Smith's User ID is jsmith, he would submit the file jsmith-hw1.pdf to canvas).  


**Quizzes**
There will be short weekly quizes on Thursdays to test the material that was taught earlier in the week.


**Final exam**
The final exam is on Friday December 16 at 8:30am.  

**Final project**
There has been some interest from graduate students to take this course.  For such students I am giving the option of a final project in place of the final exam and I would highly suggest this option for more experience in applied data analysis.  For such students a proposed topic is due Nov 3.  




<!--#include virtual="../footer.html" -->




