---
title: "Homework 4"
output: pdf_document
---

1. Chapter 8, exercise 3

2. Chapter 8, exercise 4

3. a. Suppose $X$ is a random variable that follows a normal distribution with mean $\mu = 0$ and standard deviation $\sigma = 1$.  What is $\Pr(\mu - \sigma \leq X \leq \mu + \sigma)$, $\Pr(\mu - 2 \sigma \leq X \leq \mu + 2 \sigma)$, and $\Pr(\mu - 3 \sigma \leq X \leq \mu + 3 \sigma)$?
    b. Now suppose that $X$ follows an exponential distribution with $\lambda = 1$.  What is $\Pr(\mu - \sigma \leq X \leq \mu + \sigma)$, $\Pr(\mu - 2 \sigma \leq X \leq \mu + 2 \sigma)$, and $\Pr(\mu - 3 \sigma \leq X \leq \mu + 3 \sigma)$?
    c.  Now suppose that $X$ follows a uniform distribution on $(0, 1)$.  What is $\Pr(\mu - \sigma \leq X \leq \mu + \sigma)$, $\Pr(\mu - 2 \sigma \leq X \leq \mu + 2 \sigma)$, and $\Pr(\mu - 3 \sigma \leq X \leq \mu + 3 \sigma)$?
    
4. Suppose that test scores are normally distributed with average score of $80$ and standard deviation of 7.  
    a. What is the $90$th percentile score?  Meaning, what is the lowest test score that is more than $90 \%$ of all scores?  What is the $95$th percentile score?
    b.  For a class of 20 students, what is the probability the average class score is less than $75$?
    
5. MENSA is an organization whose members possess IQs in the top $2 \%$ of the population.
a. If IQs are normally distributed, with mean 100 and a standard deviation of 16, what is the minimum IQ required for admission to MENSA?
b. If three individuals are chosen at random from the general population what is the probability that all three satisfy the minimum requirement for MENSA?

6. At a ketchup factory, the amount of ketchup that goes into bottles are supposed to be normally distributed with mean 36 oz. and standard deviation 0.1 oz. Once every 30 minutes a bottle is selected from the production line, and its contents are noted precisely. If the amount of the bottle goes below 35.8 oz. or above 36.2 oz., then the bottle will be declared defective.
    a. If the process is in control, meaning $\mu$ = 36 oz. and $\sigma$ = 0.1 oz., what is the probability that a bottle will be declared defective?
    b. In the situation of a above, what is the probability that the number of bottles found defective in eight-hour day (i.e. 16 bottles inspectioned) will be zero?
    c. In the situation of a above, what the probability that the number of bottles found defective in an eight-hour day (16 inspections) will be exactly one?
d. If the process shifts so that $\mu$ = 37 oz and $\sigma$ = 0.4 oz, what is the probability that a bottle will be declared defective?

7. State whether the following statements are true or false and explain why.
    a. The probability that the average of 20 observations will be within $0.5$ standard deviation of the population mean exceeds the probability that the average of 40 observations will be within $0.5$ standard deviations of the population mean.
    b.  If $\bar{X}$ is the average of $n > 1$ observations, then $\Pr(\bar{X} > 4)$ is larger than $\Pr(X > 4)$ if $X \sim N(8, \sigma)$.
    c. If $\bar{X}$ is the average of $n > 1$ observations from a $N(\mu, \sigma)$ distribution and $c$ is a positive number, then $\Pr(\mu - c \leq \bar{X} \leq \mu + c)$ decreases as $n$ increases.

8. Suppose that the number of tickets purchased by a student standing in line at the ticket window for an event follows a distribution with mean $\mu$ = 2.4 and standard deviation $\sigma$ = 2. Suppose that few hours before the start of one of these matches there are 100 students standing in line to purchase tickets. If only 250 tickets remain, what is the approximate probability that all 100 students will be able to purchase the tickets they desire?

9. Assuming a population standard deviation of $\sigma = 5$, how large of a sample should you take to estimate the population mean $\mu$ with a margin of error not exceeding $0.5$?

10. 