---
title: "Quiz 1 Solutions"
output: pdf_document
---

1. Suppose you throw two 4-sided dices, with sides labeled 1, 2, 3, and 4.  
    a. List the possible outcomes of the sum of the two dices and their probabilities.
    
Possibilities $\{ (1,1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4) \}$.


---------------------
| sum | probability |
|-----|-------------|
|  2  |    1/16     |
|  3  |    2/16     |
|  4  |    3/16     | 
|  5  |    4/16     |
|  6  |    3/16     |
|  7  |    2/16     |
|  8  |    1/16     |
---------------------
    
b.  Suppose that the sum is 4.  What is the probability that either dice show a 1?

    3 ways to get a 4: $\{(1, 2), (2, 1), (2, 2) \}$.  2 of these include a 1.  Therefore the probability is 2/3.

2. Suppose you meet an old friend on the street.  She says that she has two children.  

a. List out the sample space of the genders of the two children and their corresponding probabilities.  Assume independence of the two children and that boys and girls are equally likely.

| 1st child | 2nd child |
|-----------|-----------|
|    boy    |    boy    |
|    boy    |    girl   |
|    girl   |    boy    |
|    girl   |    girl   |

b. She shows you a picture of her son.  What is the conditional probability that the other child is a boy?
    
    $\Pr(\text{two boys} | \text{at least one child is a boy}) = 1/3$.  3 ways to have at least one boy and only one includes another boy.
    
c. Suppose now she tells you that the picture is of her youngest child.  What's the probability that the elder child is also a boy?

    $\Pr(\text{eldest is a boy} | \text{youngest is a boy}) = 1/2$.
