---
title: "Quiz 4 Solutions"
author: "Name: "
output: pdf_document
---

For the following problems state the distribution used and reason for doing so.  

Suppose a battery manufacturer wants to test out the lifetime of their batteries.  They expect  their batteries to last an average of 100 hours.  

a. What is the probability that a randomly tested battery will last at least 50 hours?
    
    The lifetime of the battery, $T$, is modeled as an exponential random variable with mean $\lambda^{-1} = 100$.  $\Pr(T \geq 50) = 1 - \Pr(T < 50) = 1 - (1 - e^{- 50 / 100}) = e^{-1/2}$.
    
b. If they test 10 batteries, what is the probability that all of the batteries will last longer than 50 hours?
    
If all last longer than 50 hours, then the minimum battery life is greater than 50.  We know that the minimum of 10 exponential$(\lambda = 1/100)$ is an exponential$(\lambda = 10/100)$ random variable.  Therefore the probability the minimum is greater than 50 is equal to $e^{- 50/10} = e^{-5}$.
    
c. Suppose a consumer needs 100 hours of continuous use.  What is the probability they will need more than 2 batteries to achieve 100 hours of continuous use? Assume that changing the battery takes no time and one battery is in use at a single time.
    
Two ways to solve this: Poisson or Gamma.  I'll use the Poisson.  The number of consecutive batteries, $X$, that die in a 100 hour period is a Poisson random variable with an average of $\lambda = 1$ battery that dies per 100 hour period.  $\Pr(X > 2) = 1 - \Pr(X \leq 2) = 1 - e^{-1} - 1 \cdot e^{-1}  - 1 e^{-1}/2 = 1 - 5 e^{-1}/2$
    
    
\pagebreak

Binomial$(n, p)$: \newline
    pmf: $f(x) = \binom{n}{x} p^{x} (1 - p)^{n -x}$ \newline
    expectation: $np$ \newline

Poisson$(\lambda)$: \newline
pmf: $f(x) = \lambda^{x} e^{-\lambda} / x!$ \newline
expectation: $\lambda$ \newline

Geometric$(p)$: \newline
pmf: $f(x) = (1 - p)^{x} p$ \newline
expectation: $\frac{1}{p} - 1$ \newline

Negative Binomial$(r, p)$: \newline
pmf: $f(x) = \binom{x + r - 1}{x} p^{x} (1 - p)^{r}$ \newline
expectation: $\frac{pr}{1 - p}$ \newline

Hypergeometric$(N_{1}, N_{2}, n)$: \newline 
pmf: $f(x) = \frac{\binom{N_{1}}{x} \binom{N_{2}}{n - x}}{\binom{N_{1} + N_{2}}{n}}$ \newline
expectation: $n N_{1}/ (N_{1} + N_{2})$ \newline

Uniform$(a, b)$: \newline
pdf: $f(x) = 1/(b -a)$ \newline
cdf: $F(x) = \begin{cases} 0 & x \leq a \\ (x - a)/(b - a) & a < x < b \\ 1 & x > b \end{cases}$ \newline
expectation: $(a + b)/2$ \newline

Exponential$(\lambda)$: \newline
pdf: $f(x) = \lambda e^{-\lambda x}$, $x > 0$ \newline
cdf: $F(x) = 1 - e^{-\lambda x}$, $x > 0$ \newline
expectation: $\lambda^{-1}$

Gamma$(k, \theta)$: \newline
pdf: $f(x) = x^{k - 1} e^{-x / \theta} / \big( \Gamma(k) \theta^{k} \big)$, $x > 0$ \newline
expectation: $k \theta$

Beta$(\alpha, \beta)$: \newline
pdf: $f(x) = x^{\alpha - 1} (1 - x)^{\beta - 1} / \mathcal{B} ( \alpha, \beta)$, $0 < x < 1$ \newline
expectation: $\alpha / (\alpha + \beta)$


    
    