---
title: "Quiz 6"
author: "Name: "
output: pdf_document
---

Remember to state the logic behind your answers.  If you use any variables, please state what the variables represent.

1.  Genetic testing is commonly used in prosecution to confirm the suspect's presence at a crime scene.  There are proposals to extend genetic testing to database searches, but it is known that the data in the database and input are not exact.  Suppose that we want to search a database of 10 million people.  To prevent false identification, we set a strigent threshold for matching at a $99.999 \%$ confidence level.  Supposing that each match test is independent and that the null hypotheses are correctly stated, how many incorrect matches can we expect for each search?
    \
    \
    \
    \
    \
    \
2.  Suppose that we want test a weightloss drug.  We will get 20 people to take the drug for a month and track their weight.  We want to know if the drug helps the people lose weight.  
    a. State the null and alternative hypotheses. 
    \
    \
    \
    \
    \
    \
3.  It is believed that the average level of prothrombin in a normal population is 20 mg/100 ml of blood plasma with a standard deviation of 4 mg/100 ml.  We are going to get 100 volunteers and measure their prothrombin level to see if their prothrombin levels support this level.  
    a.  State the null and alternative hypotheses.
    \
    \
   \
   \
   \
   \
    b. Suppose that after measuring the levels of the 100 volunteers we get a $99 \%$ confidence interval for the average population prothrombin level of $(20.56, 22.31)$.  Can we reject the null hypothesis at $\alpha = 0.05$?

